name: pdf_extractor
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - accelerate==1.12.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - attrs==25.4.0
      - beautifulsoup4==4.14.3
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - colorlog==6.10.1
      - dill==0.4.1
      - distro==1.9.0
      - docling==2.69.0
      - docling-core==2.60.0
      - docling-ibm-models==3.10.3
      - docling-parse==4.7.3
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.1
      - faker==40.1.2
      - filelock==3.20.3
      - filetype==1.2.0
      - fsspec==2026.1.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - jiter==0.12.0
      - jpype1==1.4.1
      - jsonlines==4.0.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonref==1.1.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - langchain==1.2.6
      - langchain-core==1.2.7
      - langchain-ollama==1.0.1
      - langchain-openai==1.1.7
      - langgraph==1.0.6
      - langgraph-checkpoint==4.0.0
      - langgraph-prebuilt==1.0.6
      - langgraph-sdk==0.3.3
      - langsmith==0.6.4
      - latex2mathml==3.78.1
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - marko==2.2.2
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - mpire==2.10.2
      - mpmath==1.3.0
      - multiprocess==0.70.19
      - networkx==3.4.2
      - numpy==2.2.6
      - ollama==0.6.1
      - omegaconf==2.3.0
      - openai==2.15.0
      - opencv-python==4.13.0.90
      - openpyxl==3.1.5
      - orjson==3.11.5
      - ormsgpack==1.12.2
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - pluggy==1.6.0
      - polyfactory==3.2.0
      - psutil==7.2.1
      - pyclipper==1.4.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pygments==2.19.2
      - pylatexenc==2.10
      - pypdfium2==5.3.0
      - python-dateutil==2.9.0.post0
      - python-docx==1.2.0
      - python-dotenv==1.2.1
      - python-pptx==1.0.2
      - pytz==2025.2
      - pywin32==311
      - pyyaml==6.0.3
      - rapidocr==3.5.0
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rpds-py==0.30.0
      - rtree==1.4.1
      - safetensors==0.7.0
      - scipy==1.15.3
      - semchunk==2.2.2
      - shapely==2.1.2
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.8.3
      - sympy==1.14.0
      - tabula-py==2.10.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tiktoken==0.12.0
      - tokenizers==0.22.2
      - torch==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - transformers==4.57.6
      - tree-sitter==0.24.0
      - tree-sitter-c==0.23.4
      - tree-sitter-javascript==0.23.1
      - tree-sitter-python==0.23.6
      - tree-sitter-typescript==0.23.2
      - typer==0.19.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - uuid-utils==0.14.0
      - xlsxwriter==3.2.9
      - xxhash==3.6.0
      - zstandard==0.25.0
prefix: C:\Users\amate\miniconda3\envs\pdf_extractor
